version: '3.9'
services:
  db:
    image: mysql:8
    container_name: crypto_wallet_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretRootPassword
      MYSQL_DATABASE: gameover
      MYSQL_USER: gameover
      MYSQL_PASSWORD: SecretPassword
    ports:
      - "3306:3306"
    networks:
      - bridge
#  app:
#    image: cryptowallet
#    container_name: crypto_wallet_app
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bookcase?createDatabaseIfNotExist=true&serverTimezone=UTC&useLegacyDatetimeCode=false
#      SPRING_DATASOURCE_USERNAME: cryptowalletUser
#      SPRING_DATASOURCE_PASSWORD: superSecretPassword
#    command: sh -c "curl https://wp.pl && ping 8.8.8.8"
#    networks:
#      - default
volumes:
  db_data:
networks:
  #  default:
  #    name: portainer_default
  #    driver: bridge
  #    ipam:
  #      config:
  #        - subnet: 172.21.0.0/16
  #          ip_range: 172.21.0.1/24
  #          gateway: 172.21.0.1
  bridge: